dotenv: ../.env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
networks:
  rinkeby:
    verify: True
  development:
    verify: False
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
