# Generated by Django 4.0.5 on 2022-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='IsRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
